version: 2
updates:
  - package-ecosystem: gradle
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 3
    target-branch: "java-package-autoupdate"
    labels:
      - "java-app"
  - package-ecosystem: npm
    directory: "/docs"
    schedule:
      interval: daily
    target-branch: "docs-package-autoupdate"
    open-pull-requests-limit: 3