name: Create release

on:
  push:
    branches:
      - main

jobs:
  build_release:
    name: Publish zip
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v4
      - name: Get next version
        uses: reecetech/version-increment@2023.9.3
        id: version
        with:
          scheme: semver
          increment: patch
      - name: Find and Replace
        uses: jacobtomlinson/gha-find-replace@v3
        with:
          find: "version.*"
          replace: "version=${{ steps.version.outputs.version }}"
          regex: true
          include: "src/main/resources/version.properties"
      - uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'oracle'
      - run: ./gradlew clean createTar --no-daemon
      - name: Publish new version
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.PAT }}
          file: "build/distributions/k3s-simplifier.tar.gz"
          tag: ${{ steps.version.outputs.version }}
          overwrite: true
          body: "Creating the zip"