# Simple workflow for deploying static content to GitHub Pages
name: Deploy static content to Pages
run-name: Deploy Docs to github pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  # Single deploy job since we're just deploying
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - name: Check for changes in 'docs' directory
        id: check_changes
        run: |
          if git diff-tree --name-only --no-commit-id ${{ github.sha }} | grep -q "^docs"; then
            echo "changes_made=yes" >> "$GITHUB_ENV"
          else
            echo "changes_made=no" >> "$GITHUB_ENV"
          fi
      - uses: actions/setup-node@v3
        if: ${{env.changes_made == 'yes'}}
        with:
          node-version: 18
      - name: Install dependencies
        if: ${{env.changes_made == 'yes'}}
        working-directory: docs
        run: npm install
      - name: Install dependencies
        if: ${{env.changes_made == 'yes'}}
        working-directory: docs
        run: npm ci
      - name: Build website
        if: ${{env.changes_made == 'yes'}}
        working-directory: docs
        run: npm run build
      - name: Setup Pages
        if: ${{env.changes_made == 'yes'}}
        uses: actions/configure-pages@v4
      - name: Upload artifact
        if: ${{env.changes_made == 'yes'}}
        uses: actions/upload-pages-artifact@v3
        with:
          # Upload entire repository
          path: './docs/build'
      - name: Deploy to GitHub Pages
        if: ${{env.changes_made == 'yes'}}
        id: deployment
        uses: actions/deploy-pages@v4
      - id: job_successful
        if: ${{env.changes_made == 'yes'}}
        run: echo "job_successful=yes" >> "$GITHUB_OUTPUT"
